openapi: 3.0.0
info:
  title: Yunz API
  version: 1.0.0
  description: API documentation for Yunz's portfolio
servers:
  - url: /api
paths:
  /work/{limit}:
    get:
      summary: Get work experience items
      description: Returns a list of work experience items up to the specified limit
      parameters:
        - in: path
          name: limit
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 100
          description: Number of work items to return
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/WorkItem'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  schemas:
    WorkItem:
      type: object
      required:
        - id
        - title
        - description
        - startDate
        - technologies
      properties:
        id:
          type: integer
          description: Unique identifier for the work item
        title:
          type: string
          description: Job title
        description:
          type: string
          description: Job description
        startDate:
          type: string
          format: date
          description: Start date of employment
        endDate:
          type: string
          format: date
          nullable: true
          description: End date of employment (null if current)
        technologies:
          type: array
          items:
            type: string
          description: Technologies used in the role
